server:
  port: 8081
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

security:
#  basic:
#    enabled: false
  oauth2:
    client:
      access-token-uri:   http://localhost:8099/auth/oauth/token
      user-authorization-uri: http://localhost:8099/auth/oauth/authorize
      client-id: acme
      client-secret: acmesecret
    resource:
      userInfoUri: http://localhost:8099/auth/user


zuul:
  ignoredServices: '*'
  routes:
    user-management: /user-api/**
    catalog-management: /catalog-management-api/**

    oauth-service:
      path: /auth/**
      strip-prefix: false
      sensitiveHeaders:

logging:
  level:
    org.springframework.security: debug
    org.springframework.cloud.security.oauth2: Trace


    
