server:
  port: 8081
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

management:
  security:
    user:
      username: bob
      password: secret
    oauth2:    
      client:
        accessTokenUri: http://localhost:8099/oauth/token
        userAuthorizationUri: http://localhost:8099/dialog/authorize
        clientId: xyz123
        clientSecret: ssh-password   
      resource:
        userInfoUri: http://localhost:8099/api/userinfo
        preferTokenInfo: false  
    sessions: ALWAYS

zuul:
  ignoredServices: '*'
  routes:
    user-management: /user-api/**
    catalog-management: /catalog-management-api/**
