server:
  port: 8081
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

security:
#  basic:
#    enabled: false
  oauth2:
    client:
      access-token-uri: http://localhost:8099/oauth/token
      user-authorization-uri: http://localhost:8099/dialog/authorize
      client-id: xyz123
      client-secret: ssh-password
    resource:
      userInfoUri: http://localhost:8099/api/clientinfo 


zuul:
  ignoredServices: '*'
  routes:
    user-management: /user-api/**
    catalog-management: /catalog-management-api/**

logging:
  level:
    org.springframework.security: debug
    org.springframework.cloud.security.oauth2: Trace


    
