server:
  port: 8081
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

zuul:
  ignoredServices: '*'
  routes:
    user-service: /user-api/**
    product-service: /product-api/**
