server:
  port: 8081
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

management:
  security:
    enabled: false

zuul:
  ignoredServices: '*'
  routes:
    user-management: /user-api/**
    catalog-management: /catalog-management-api/**
